#!/bin/bash
## This is to print something with echo
echo Hello World

## Print multiple lines
echo Hello World line 1
echo Hello World line 2

## Print with single echo command
echo -e "Hello World line1\nHello World line2"

## Print tab spaces
echo -e "Serial No\tCandidate Name\t\tCourse Name\n1.\t\tAnoop\t\t\tDevops\n2.\t\tKumar\t\t\tAWS"

##Print with colors
echo -e "\e[31mHello World with red color foreground\e[0m"

echo -e "Hello World with default foregroud"

## Print with colors with background also
echo -e "\e[42;31mThis is for red on green\e[0m"
#############




