#!/bin/bash
## This is to print something with echo
echo Hello World

## Now i want to print multiple lines using single echo command
echo -e "This is the first line\nThis is the second line"

## Print with tab spaces
echo -e "1.\tAnoop\t\tDevOps\n2.\tNithish\t\tSAP"

## Printing with colors
echo -e "\e[31mRed color foreground"

## This is for updated color Printing
echo -e "\e[31;44This is red color or blue back"
