#!/bin/bash

## This is forgenral type of variables
name=Anoop
course=Devops
duration="2 months"

echo "Hello $name, Welcome to $course class and the duration of this course is $duration"

## This is for accessing local variable as environment variable
echo "Hello Anoop, Welcome $class class"




