#!/bin/bash
## This is for using variables
Stength=43
Class=DevOps
echo "Welcome to $Class training and our Stength is $Stength"
echo "Welcome to ${Class} training and our Strength is ${Stength}"

## This is to convert local variable to environment variable
echo "Welcome to $class training"

## 

