#!/bin/bash
## This is for simple read inputs
##read -p 'Enter your name:' name
##read -p 'Enter your course:' course
echo -e "\e[31mHello $name, Welcome to $course class, your password is $pass\e[0m"
###
