#!/bin/bash
## This is to check how read input works
read -p 'Enter your name: ' name
read -p 'Enter your course: ' course

## For password read
read -s -p 'Enter your password: ' pass

echo -e "\nHello $name, Welcome to $course class and your password is $pass"
####
