#!/bin/bash 

action=$1
## Color Codes 
R="\e[31m"
N="\e[0m"

case $action in 
    start) 
        echo -e "Starting the service"
        ;; 
    stop) 
        echo -e "Stopping the service"
        ;;
    *)
        echo "Usage:: $0 start|stop"
        echo -e "\t ${R}start${N} -> Start the service"
        echo -e "\t ${R}stop${N}  -> Stop the service"
        exit 1
        ;;
esac
#############
